### ISSUE TITLE
SyntaxError: invalid token - Error during install

### ISSUE THREAD

**Issue by rosarch** [rossigee/backups#11]
Hi, this seemed to be exactly what I was after, thanks for putting the effort into putting it together.

Not sure if this is me doing something simple wrong.

I am using Ubuntu Server 20.04

Steps to recreate:

- git clone repo
- run ` sudo python3.8 setup.py build`
- run `sudo python3.7 setup.py install`

When I run this I get an error:
`byte-compiling build/bdist.linux-x86_64/egg/backups/destinations/samba.py to samba.cpython-37.pyc
  File "build/bdist.linux-x86_64/egg/backups/destinations/samba.py", line 31
    os.chmod(credsfilename, 0400)
                               ^
SyntaxError: invalid token
`

When I run a test following this I get another error, guessing that is because of an issue with the install

`sudo -H -u <user> /usr/local/bin/backup -v /home/<user>/repos/backups/mynightlybackup.cfg`

`Traceback (most recent call last):
  File "/usr/local/bin/backup", line 11, in <module>
    load_entry_point('backups==2.2.0', 'console_scripts', 'backup')()
  File "/usr/local/lib/python3.8/dist-packages/backups-2.2.0-py3.8.egg/backups/main.py", line 124, in main
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 3 (char 85)
`
Any help will be gratefully appreciated :-)

**Comment by rossigee** [comment]
Hi @rosarch,

The main things I can see from your report...

* You really don't need to 'sudo' to build the package. You should not need to build the package as the root user.
* I don't understand why you're trying to use one version of python to build and another to install. I suspect this is the cause of the first error.
* The 'Expecting value' error coming from JSONDecodeError suggests your config file isn't valid JSON. You can check this with a tool like 'json_pp', and fix any errors it show you:

```
$ json_pp < mynightlybackup.cfg
```

I'm also working with Ubuntu 20.04, and `python3 setup.py build && sudo python setup.py install` work fine for me, so it looks like it might be an issue local to your environment.

**Comment by rosarch** [comment]
Thanks for really quick response, will give it another shot 👍
